spring:
    datasource:
        url: jdbc:mysql://localhost/ProduitsDB?createDatabaseIfNotExist=true
        username: root
        password: Pa$$w0rd
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update